const RESERVATION_STATUS = {
  PENDING_CONFIRM: "待确认",
  WAITING_ARRIVAL: "待到店",
  WAITING_REVIEW: "待核实",
  ARRIVED: "已到店",
  IN_SERVICE: "进行中",
  COMPLETED: "已完成",
  CANCELED: "已取消",
  NO_SHOW: "未到店",
  RELEASED: "已释放"
};

const TABLE_STATUS = {
  FREE: "空闲",
  RESERVED: "已预约",
  USING: "使用中",
  CLEANING: "清洁中",
  REPAIRING: "维修中",
  DISABLED: "停用"
};

const ASSISTANT_RESERVATION_STATUS = {
  PENDING_CONFIRM: "待确认",
  CONFIRMED: "已确认",
  COMPLETED: "已完成",
  CANCELED: "已取消"
};

const CAMPAIGN_REGISTRATION_STATUS = {
  PENDING_REVIEW: "待审核",
  SUCCESS: "报名成功",
  CANCELED: "已取消"
};

const ACTIVE_RESERVATION_STATUSES = [
  RESERVATION_STATUS.PENDING_CONFIRM,
  RESERVATION_STATUS.WAITING_ARRIVAL,
  RESERVATION_STATUS.WAITING_REVIEW,
  RESERVATION_STATUS.ARRIVED,
  RESERVATION_STATUS.IN_SERVICE
];

const ACTIVE_ASSISTANT_RESERVATION_STATUSES = [
  ASSISTANT_RESERVATION_STATUS.PENDING_CONFIRM,
  ASSISTANT_RESERVATION_STATUS.CONFIRMED
];

const NO_SHOW_LOCK_DAYS = 3;
const RESERVATION_LEAD_MINUTES = 30;

module.exports = {
  ACTIVE_RESERVATION_STATUSES,
  ACTIVE_ASSISTANT_RESERVATION_STATUSES,
  ASSISTANT_RESERVATION_STATUS,
  CAMPAIGN_REGISTRATION_STATUS,
  NO_SHOW_LOCK_DAYS,
  RESERVATION_LEAD_MINUTES,
  RESERVATION_STATUS,
  TABLE_STATUS
};
