const RESERVATION_STATUS = {
  PENDING_CONFIRM: "pending_confirm",
  WAITING_ARRIVAL: "pending_arrival",
  WAITING_REVIEW: "pending_verify",
  ARRIVED: "arrived",
  IN_SERVICE: "in_progress",
  COMPLETED: "completed",
  CANCELED: "canceled",
  NO_SHOW: "no_show",
  RELEASED: "released"
};

const TABLE_STATUS = {
  FREE: "idle",
  RESERVED: "reserved",
  USING: "in_use",
  CLEANING: "cleaning",
  REPAIRING: "repairing",
  DISABLED: "disabled"
};

const ASSISTANT_STATUS = {
  OFF_SHIFT: "off_shift",
  IDLE: "idle",
  RESERVED: "reserved",
  SERVING: "serving",
  RESTING: "resting",
  CHECKED_OUT: "checked_out"
};

const ASSISTANT_RESERVATION_STATUS = {
  PENDING_CONFIRM: "pending_confirm",
  CONFIRMED: "confirmed",
  SERVING: "serving",
  COMPLETED: "completed",
  CANCELED: "canceled",
  NO_SHOW: "no_show"
};

const CAMPAIGN_REGISTRATION_STATUS = {
  PENDING_REVIEW: "pending_review",
  SUCCESS: "approved",
  REJECTED: "rejected",
  CANCELED: "canceled"
};

const NO_SHOW_STATUS = {
  ACTIVE: "active",
  LIFTED: "lifted",
  EXPIRED: "expired"
};

const ACTIVE_RESERVATION_STATUSES = [
  RESERVATION_STATUS.PENDING_CONFIRM,
  RESERVATION_STATUS.WAITING_ARRIVAL,
  RESERVATION_STATUS.WAITING_REVIEW,
  RESERVATION_STATUS.ARRIVED,
  RESERVATION_STATUS.IN_SERVICE
];

const ACTIVE_ASSISTANT_RESERVATION_STATUSES = [
  ASSISTANT_RESERVATION_STATUS.PENDING_CONFIRM,
  ASSISTANT_RESERVATION_STATUS.CONFIRMED,
  ASSISTANT_RESERVATION_STATUS.SERVING
];

const NO_SHOW_LOCK_DAYS = 3;
const RESERVATION_LEAD_MINUTES = 30;

module.exports = {
  ACTIVE_ASSISTANT_RESERVATION_STATUSES,
  ACTIVE_RESERVATION_STATUSES,
  ASSISTANT_RESERVATION_STATUS,
  ASSISTANT_STATUS,
  CAMPAIGN_REGISTRATION_STATUS,
  NO_SHOW_LOCK_DAYS,
  NO_SHOW_STATUS,
  RESERVATION_LEAD_MINUTES,
  RESERVATION_STATUS,
  TABLE_STATUS
};
